site_name: Coding
home_url: 'https://saschakiesow.de'
theme:
    name: 'material'
    custom_dir: '../mkdocs-material/material/'
    favicon: 'images/favicon.ico'
    logo: 'images/logo.png'
    font:
        text: 'Montserrat'
        code: 'Roboto Mono'
repo_name: 'tippi09/wikiesow'
repo_url: 'https://github.com/tippi09/wikiesow'
copyright: '&copy; 2019 Sascha Kiesow'
extra:
    social:
        - type: 'github'
          link: 'https://github.com/tippi09'
