site_name: Coding
home_url: 'https://saschakiesow.de'
theme:
    name: 'material'
    custom_dir: '../mkdocs-material/material/'
    favicon: 'images/favicon.ico'
    logo: 'images/logo.png'
    font:
        text: 'Montserrat'
        code: 'Roboto Mono'
repo_name: 'tippi09/wikiesow'
repo_url: 'https://github.com/tippi09/wikiesow'
copyright: '&copy; 2019 Sascha Kiesow'
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
